In [37]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [38]:
df = pd.read_excel('Providers.xlsx').drop(columns=['№'])
df.head()

,Наименование,Регистрационный номер,Наименование полное,Адрес (место нахождения),Руководитель - ФИО,Телефон,Электронный адрес,Дата регистрации,"Возраст компании, лет",Вид деятельности/отрасль,...,"2022, Коэффициент оборачиваемости совокупных активов, %","2022, Валовая рентабельность, %","2022, Рентабельность продаж, %","2022, Доля себестоимости как процент от выручки, %","2022, Рентабельность активов (ROA), %","2022, Рентабельность капитала (ROE), %","2022, Рентабельность активов (п. 1.6 ст.105.8 НК РФ), %","2022, Коэффициент текущей ликвидности, %","2022, Коэффициент быстрой ликвидности, %","2022, Коэффициент абсолютной ликвидности, %"
0,"1-АЯ ВАТЕР КОМПАНИ, ООО",1142651006398,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""1-АЯ...","357202, Ставропольский край, г.о. Минераловодс...",Коптиевский Вадим Валерьевич,+7 (879) 3259919,NaN,2014-03-18,9.0,"Торговля оптовая соками, минеральной водой и п...",...,6.2,NaN,0.1,0.9,0.2,0.5,NaN,1.6,1.0,NaN
1,"108 ЧК, ООО",1080276000298,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""108 ЧК""","450071, Башкортостан респ., г. Уфа, ул. Мендел...",Мухамадиева Динара Фандусовна,+7 (347) 2374074,NaN,2008-01-31,15.0,"Торговля оптовая кофе, чаем, какао и пряностями",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"13 УСТРИЦ, ООО",1197746593835,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""13 У...","107553, г. Москва, вн.тер.г. муниципальный окр...",Буторина Екатерина Владимировна,NaN,NaN,2019-10-03,3.5,"Торговля оптовая рыбой, ракообразными и моллюс...",...,1.9,NaN,0.0,1.0,0.0,0.4,NaN,1.2,0.9,0.1
3,"16-Я РЕСПУБЛИКА, ООО",1167847127953,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""16-Я...","197136, г. Санкт-Петербург, вн.тер.г. муниципа...",Жилина Галина Ивановна,+7 (495) 0035916\n+7 (800) 1001681,NaN,2016-03-11,7.0,Торговля оптовая неспециализированная пищевыми...,...,0.8,NaN,0.2,0.8,NaN,NaN,NaN,4.3,0.5,0.2
4,"21 ВЕК, ООО",1121103001018,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""21 ВЕК""","169912, Коми респ., г. Воркута, набережная Шах...",Закирова Наталья Николаевна,+7 (82151) 55207,emir77@list.ru,2012-05-23,11.0,Торговля оптовая пивом,...,33.1,0.1,0.1,0.9,1.9,6.3,9.5,NaN,NaN,NaN

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 42 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Наименование                                                                                10000 non-null  object
 1   Регистрационный номер                                                                       10000 non-null  int64
 2   Наименование полное                                                                         10000 non-null  object
 3   Адрес (место нахождения)                                                                    10000 non-null  object
 4   Руководитель - ФИО                                                                          9998 non-null   object
 5   Телефон                                                                                     7777 non-null   object
 6   Электронный адрес                                                                           3576 non-null   object
 7   Дата регистрации                                                                            10000 non-null  datetime64[ns]
 8   Возраст компании, лет                                                                       10000 non-null  float64
 9   Вид деятельности/отрасль                                                                    9998 non-null   object
 10  Сводный индикатор                                                                           9894 non-null   object
 11  Предмет поставки                                                                            2304 non-null   object
 12  Размер компании                                                                             7622 non-null   object
 13  2022, Среднесписочная численность работников                                                7681 non-null   object
 14  Уставный капитал, RUB                                                                       9955 non-null   float64
 15  Важная информация                                                                           2177 non-null   object
 16  2022, Запасы, RUB                                                                           6536 non-null   float64
 17  2022, Уставный капитал , RUB                                                                4426 non-null   float64
 18  2022, Себестоимость продаж, RUB                                                             6940 non-null   float64
 19  2022, Поступления от текущих операций, RUB                                                  2074 non-null   float64
 20  2022, Поступления от продаж, RUB                                                            2008 non-null   float64
 21  2022, Поступления арендных, лицензионных, комиссионных платежей, роялти, RUB                229 non-null    float64
 22  2022, Поступления от перепродажи финансовых вложений, RUB                                   7 non-null      float64
 23  2022, Платежи поставщикам и подрядчикам, RUB                                                2045 non-null   float64
 24  2022, Поступления от инвестиционных операций, RUB                                           770 non-null    float64
 25  2022, Получение дивидендов, процентов, RUB                                                  340 non-null    float64
 26  2022, Поступления от выпуска акций, увеличения долей участия, RUB                           7 non-null      float64
 27  2022, Поступления от выпуска облигаций, векселей и других долговых ценных бумаг и др., RUB  5 non-null      float64
 28  2022, Оборачиваемость основных средств, разы                                                4274 non-null   float64
 29  2022, Период оборота основных средств, дни                                                  4132 non-null   float64
 30  2022, Период оборота активов, дни                                                           6845 non-null   float64
 31  2022, Соотношение валовой прибыли к активам компании, %                                     3923 non-null   float64
 32  2022, Коэффициент оборачиваемости совокупных активов, %                                     6855 non-null   float64
 33  2022, Валовая рентабельность, %                                                             3907 non-null   float64
 34  2022, Рентабельность продаж, %                                                              6833 non-null   float64
 35  2022, Доля себестоимости как процент от выручки, %                                          6754 non-null   float64
 36  2022, Рентабельность активов (ROA), %                                                       7279 non-null   float64
 37  2022, Рентабельность капитала (ROE), %                                                      7288 non-null   float64
 38  2022, Рентабельность активов (п. 1.6 ст.105.8 НК РФ), %                                     4034 non-null   float64
 39  2022, Коэффициент текущей ликвидности, %                                                    7464 non-null   float64
 40  2022, Коэффициент быстрой ликвидности, %                                                    7436 non-null   float64
 41  2022, Коэффициент абсолютной ликвидности, %                                                 6957 non-null   float64
dtypes: datetime64[ns](1), float64(28), int64(1), object(12)
memory usage: 3.2+ MB

In [40]:
df.nunique()

Наименование                                                                                   8471
Регистрационный номер                                                                         10000
Наименование полное                                                                            8557
Адрес (место нахождения)                                                                       9746
Руководитель - ФИО                                                                             9535
Телефон                                                                                        7706
Электронный адрес                                                                              3537
Дата регистрации                                                                               4664
Возраст компании, лет                                                                            67
Вид деятельности/отрасль                                                                         47
Сводный индикатор                                                                                 3
Предмет поставки                                                                               2113
Размер компании                                                                                   4
2022, Среднесписочная численность работников                                                    299
Уставный капитал, RUB                                                                           920
Важная информация                                                                              2012
2022, Запасы, RUB                                                                              5614
2022, Уставный капитал , RUB                                                                    490
2022, Себестоимость продаж, RUB                                                                6723
2022, Поступления от текущих операций, RUB                                                     2064
2022, Поступления от продаж, RUB                                                               2004
2022, Поступления арендных, лицензионных, комиссионных платежей, роялти, RUB                    226
2022, Поступления от перепродажи финансовых вложений, RUB                                         7
2022, Платежи поставщикам и подрядчикам, RUB                                                   2031
2022, Поступления от инвестиционных операций, RUB                                               714
2022, Получение дивидендов, процентов, RUB                                                      323
2022, Поступления от выпуска акций, увеличения долей участия, RUB                                 7
2022, Поступления от выпуска облигаций, векселей и других долговых ценных бумаг и др., RUB        5
2022, Оборачиваемость основных средств, разы                                                   2491
2022, Период оборота основных средств, дни                                                     1003
2022, Период оборота активов, дни                                                              1416
2022, Соотношение валовой прибыли к активам компании, %                                        3371
2022, Коэффициент оборачиваемости совокупных активов, %                                        6565
2022, Валовая рентабельность, %                                                                2483
2022, Рентабельность продаж, %                                                                 2729
2022, Доля себестоимости как процент от выручки, %                                             3374
2022, Рентабельность активов (ROA), %                                                          3854
2022, Рентабельность капитала (ROE), %                                                         5440
2022, Рентабельность активов (п. 1.6 ст.105.8 НК РФ), %                                        2973
2022, Коэффициент текущей ликвидности, %                                                       6671
2022, Коэффициент быстрой ликвидности, %                                                       6602
2022, Коэффициент абсолютной ликвидности, %                                                    3651
dtype: int64

In [41]:
df.isna().sum().sort_values(ascending=True)

Наименование                                                                                     0
Дата регистрации                                                                                 0
Адрес (место нахождения)                                                                         0
Возраст компании, лет                                                                            0
Регистрационный номер                                                                            0
Наименование полное                                                                              0
Руководитель - ФИО                                                                               2
Вид деятельности/отрасль                                                                         2
Уставный капитал, RUB                                                                           45
Сводный индикатор                                                                              106
Телефон                                                                                       2223
2022, Среднесписочная численность работников                                                  2319
Размер компании                                                                               2378
2022, Коэффициент текущей ликвидности, %                                                      2536
2022, Коэффициент быстрой ликвидности, %                                                      2564
2022, Рентабельность капитала (ROE), %                                                        2712
2022, Рентабельность активов (ROA), %                                                         2721
2022, Коэффициент абсолютной ликвидности, %                                                   3043
2022, Себестоимость продаж, RUB                                                               3060
2022, Коэффициент оборачиваемости совокупных активов, %                                       3145
2022, Период оборота активов, дни                                                             3155
2022, Рентабельность продаж, %                                                                3167
2022, Доля себестоимости как процент от выручки, %                                            3246
2022, Запасы, RUB                                                                             3464
2022, Уставный капитал , RUB                                                                  5574
2022, Оборачиваемость основных средств, разы                                                  5726
2022, Период оборота основных средств, дни                                                    5868
2022, Рентабельность активов (п. 1.6 ст.105.8 НК РФ), %                                       5966
2022, Соотношение валовой прибыли к активам компании, %                                       6077
2022, Валовая рентабельность, %                                                               6093
Электронный адрес                                                                             6424
Предмет поставки                                                                              7696
Важная информация                                                                             7823
2022, Поступления от текущих операций, RUB                                                    7926
2022, Платежи поставщикам и подрядчикам, RUB                                                  7955
2022, Поступления от продаж, RUB                                                              7992
2022, Поступления от инвестиционных операций, RUB                                             9230
2022, Получение дивидендов, процентов, RUB                                                    9660
2022, Поступления арендных, лицензионных, комиссионных платежей, роялти, RUB                  9771
2022, Поступления от перепродажи финансовых вложений, RUB                                     9993
2022, Поступления от выпуска акций, увеличения долей участия, RUB                             9993
2022, Поступления от выпуска облигаций, векселей и других долговых ценных бумаг и др., RUB    9995
dtype: int64

In [42]:
df = df.drop([
#     'Телефон', 
         '2022, Среднесписочная численность работников', 
         'Размер компании', 
         '2022, Коэффициент текущей ликвидности, %', 
         '2022, Коэффициент быстрой ликвидности, %', 
         '2022, Рентабельность капитала (ROE), %', 
         '2022, Рентабельность активов (ROA), %', 
         '2022, Коэффициент абсолютной ликвидности, %', 
         '2022, Себестоимость продаж, RUB', 
         '2022, Коэффициент оборачиваемости совокупных активов, %', 
         '2022, Период оборота активов, дни', 
         '2022, Рентабельность продаж, %', 
         '2022, Доля себестоимости как процент от выручки, %', 
         '2022, Запасы, RUB', 
         '2022, Уставный капитал , RUB', 
         '2022, Оборачиваемость основных средств, разы', 
         '2022, Период оборота основных средств, дни', 
         '2022, Рентабельность активов (п. 1.6 ст.105.8 НК РФ), %', 
         '2022, Соотношение валовой прибыли к активам компании, %', 
         '2022, Валовая рентабельность, %', 'Электронный адрес', 
#          'Предмет поставки', 
#          'Важная информация', 
         '2022, Поступления от текущих операций, RUB', 
         '2022, Платежи поставщикам и подрядчикам, RUB', 
         '2022, Поступления от продаж, RUB', 
         '2022, Поступления от инвестиционных операций, RUB', 
         '2022, Получение дивидендов, процентов, RUB', 
         '2022, Поступления арендных, лицензионных, комиссионных платежей, роялти, RUB', 
         '2022, Поступления от перепродажи финансовых вложений, RUB', 
         '2022, Поступления от выпуска акций, увеличения долей участия, RUB', 
         '2022, Поступления от выпуска облигаций, векселей и других долговых ценных бумаг и др., RUB'], axis=1)

a = ['Сводный индикатор', 'Уставный капитал, RUB', 'Вид деятельности/отрасль', 'Руководитель - ФИО']
for col in a:
    df = df[df[col].notna()]

In [43]:
df.isna().sum().sort_values(ascending=True)

Наименование                   0
Регистрационный номер          0
Наименование полное            0
Адрес (место нахождения)       0
Руководитель - ФИО             0
Дата регистрации               0
Возраст компании, лет          0
Вид деятельности/отрасль       0
Сводный индикатор              0
Уставный капитал, RUB          0
Телефон                     2193
Предмет поставки            7604
Важная информация           7749
dtype: int64

In [44]:
pd.options.display.float_format = '{:.1f}'.format
df.describe()

       Регистрационный номер  Возраст компании, лет  Уставный капитал, RUB
count                 9891.0                 9891.0                 9891.0
mean         1224438068593.1                   11.3              5156675.4
std           626619862853.4                    6.6             86505039.8
min          1020100695493.0                    0.0                   10.0
25%          1084632010401.5                    6.5                10000.0
50%          1140280064132.0                    9.5                10000.0
75%          1167847157702.5                   15.0               100000.0
max          5187746031017.0                   35.5           5132980000.0

In [45]:
df['Сводный индикатор']

0        Низкий риск
1       Средний риск
2        Низкий риск
3       Высокий риск
4        Низкий риск
            ...
9994     Низкий риск
9995    Высокий риск
9996    Высокий риск
9997     Низкий риск
9998     Низкий риск
Name: Сводный индикатор, Length: 9891, dtype: object

In [46]:
df = df.reset_index().drop(['index'], axis=1)

In [47]:
df

,Наименование,Регистрационный номер,Наименование полное,Адрес (место нахождения),Руководитель - ФИО,Телефон,Дата регистрации,"Возраст компании, лет",Вид деятельности/отрасль,Сводный индикатор,Предмет поставки,"Уставный капитал, RUB",Важная информация
0,"1-АЯ ВАТЕР КОМПАНИ, ООО",1142651006398,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""1-АЯ...","357202, Ставропольский край, г.о. Минераловодс...",Коптиевский Вадим Валерьевич,+7 (879) 3259919,2014-03-18,9.0,"Торговля оптовая соками, минеральной водой и п...",Низкий риск,NaN,100000.0,NaN
1,"108 ЧК, ООО",1080276000298,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""108 ЧК""","450071, Башкортостан респ., г. Уфа, ул. Мендел...",Мухамадиева Динара Фандусовна,+7 (347) 2374074,2008-01-31,15.0,"Торговля оптовая кофе, чаем, какао и пряностями",Средний риск,NaN,10000.0,На 24.05.2023 22:06 имеются действующие решени...
2,"13 УСТРИЦ, ООО",1197746593835,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""13 У...","107553, г. Москва, вн.тер.г. муниципальный окр...",Буторина Екатерина Владимировна,NaN,2019-10-03,3.5,"Торговля оптовая рыбой, ракообразными и моллюс...",Низкий риск,NaN,25000.0,NaN
3,"16-Я РЕСПУБЛИКА, ООО",1167847127953,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""16-Я...","197136, г. Санкт-Петербург, вн.тер.г. муниципа...",Жилина Галина Ивановна,+7 (495) 0035916\n+7 (800) 1001681,2016-03-11,7.0,Торговля оптовая неспециализированная пищевыми...,Высокий риск,NaN,10000.0,NaN
4,"21 ВЕК, ООО",1121103001018,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""21 ВЕК""","169912, Коми респ., г. Воркута, набережная Шах...",Закирова Наталья Николаевна,+7 (82151) 55207,2012-05-23,11.0,Торговля оптовая пивом,Низкий риск,NaN,10000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9886,"ЯГОДЫ МИКС, ООО",1203600019842,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЯГОД...","394019, Воронежская обл., г. Воронеж, проспект...",Мильнер Роман Владимирович,NaN,2020-07-07,2.5,Торговля оптовая фруктами и овощами,Низкий риск,NaN,20000.0,NaN
9887,"ЯГОДЫ СИБИРИ, ООО",1177746445250,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЯГОД...","117638, г. Москва, ул. Сивашская, д. 6 к. 1 эт...",Лебедева Олеся Олеговна,+7 (905) 7703286,2017-05-02,6.0,Торговля оптовая фруктами и овощами,Высокий риск,NaN,300000.0,NaN
9888,"ЯГУАР, ООО",1042127014236,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЯГУАР""","428006, Чувашская Республика - Чувашия, г. Чеб...",Мухин Дмитрий Алексеевич,+7 (8352) 632320\n+7 (8352) 635657\n+7 (8352) ...,2004-08-11,18.5,Торговля оптовая напитками,Высокий риск,NaN,10090000.0,На 19.03.2023 22:05 имеются действующие решени...
9889,"ЯГУАР, ООО",1159102132640,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЯГУАР""","298603, Крым респ., г. Ялта, ул. Свердлова, д....",Буздаков Антон Александрович,+7 (978) 1273228\n+7 (978) 7407340,2015-12-25,7.0,Торговля оптовая фруктами и овощами,Низкий риск,01.24.29.110 Черешня\n01.25.31.000 Миндаль\n01...,10000.0,NaN
9890,"ЯДРИНСКИЙ КООПТОРГ, ООО",1192130009026,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЯДРИ...","429060, Чувашская Республика - Чувашия, Ядринс...",Казамбаева Людмила Виссарионовна,+7 (960) 3065036,2019-08-13,3.5,Торговля оптовая неспециализированная пищевыми...,Низкий риск,NaN,250000.0,NaN

In [48]:
industries = df['Вид деятельности/отрасль'].tolist()
suppliers = df['Наименование'].tolist()
reg_num = df['Регистрационный номер'].tolist()

In [49]:
# import random
# from random import shuffle

# np.set_printoptions(precision=1, floatmode='fixed')
# matrix =[0]*25

# for i in range(25):
#     random_number = np.random.randint(1, len(df.columns.tolist())*0.2+1)
#     r = np.random.default_rng().choice(np.arange(0, 5.1, 0.1).tolist(), random_number).tolist()+['empty']*(len(suppliers)-random_number)
#     random.shuffle(r)
#     matrix[i] = r

In [50]:
# ratings = pd.DataFrame(matrix, columns=df.index.tolist()).replace('empty', np.nan)
# ratings.head()

In [51]:
# len(ratings.columns.tolist())

In [52]:
# len(df.index.tolist())

In [53]:
# dic = {}
# for n in df.index.tolist():
#     dic[n] = df.iloc[n, 1]

In [54]:
# len(dic)

In [55]:
# ratings.nunique()

In [56]:
# ratings.to_csv('ratings.csv')

In [57]:
# ratings = pd.read_csv('ratings.csv')
# ratings.columns = ratings.columns.str.replace('Unnamed: 0', 'User_id')

# ratings = pd.melt(ratings, id_vars='User_id', value_vars=ratings.columns[1:]).sort_values(by='User_id').dropna()
# ratings.columns = ratings.columns.str.replace('value', 'rating')
# ratings.columns = ratings.columns.str.replace('variable', 'Registration number')
# ratings.head()

In [58]:
# ratings.to_csv('ratings.csv')

In [59]:
# df = pd.read_excel('Providers.xlsx').drop(columns=['№'])
providers = df[['Регистрационный номер', 'Наименование', 'Вид деятельности/отрасль', 'Телефон', 
                'Предмет поставки', 'Важная информация', 'Сводный индикатор', 'Уставный капитал, RUB',
                'Руководитель - ФИО']].rename_axis('Registration number').reset_index()
providers.head()

,Registration number,Регистрационный номер,Наименование,Вид деятельности/отрасль,Телефон,Предмет поставки,Важная информация,Сводный индикатор,"Уставный капитал, RUB",Руководитель - ФИО
0,0,1142651006398,"1-АЯ ВАТЕР КОМПАНИ, ООО","Торговля оптовая соками, минеральной водой и п...",+7 (879) 3259919,NaN,NaN,Низкий риск,100000.0,Коптиевский Вадим Валерьевич
1,1,1080276000298,"108 ЧК, ООО","Торговля оптовая кофе, чаем, какао и пряностями",+7 (347) 2374074,NaN,На 24.05.2023 22:06 имеются действующие решени...,Средний риск,10000.0,Мухамадиева Динара Фандусовна
2,2,1197746593835,"13 УСТРИЦ, ООО","Торговля оптовая рыбой, ракообразными и моллюс...",NaN,NaN,NaN,Низкий риск,25000.0,Буторина Екатерина Владимировна
3,3,1167847127953,"16-Я РЕСПУБЛИКА, ООО",Торговля оптовая неспециализированная пищевыми...,+7 (495) 0035916\n+7 (800) 1001681,NaN,NaN,Высокий риск,10000.0,Жилина Галина Ивановна
4,4,1121103001018,"21 ВЕК, ООО",Торговля оптовая пивом,+7 (82151) 55207,NaN,NaN,Низкий риск,10000.0,Закирова Наталья Николаевна

In [60]:
providers

,Registration number,Регистрационный номер,Наименование,Вид деятельности/отрасль,Телефон,Предмет поставки,Важная информация,Сводный индикатор,"Уставный капитал, RUB",Руководитель - ФИО
0,0,1142651006398,"1-АЯ ВАТЕР КОМПАНИ, ООО","Торговля оптовая соками, минеральной водой и п...",+7 (879) 3259919,NaN,NaN,Низкий риск,100000.0,Коптиевский Вадим Валерьевич
1,1,1080276000298,"108 ЧК, ООО","Торговля оптовая кофе, чаем, какао и пряностями",+7 (347) 2374074,NaN,На 24.05.2023 22:06 имеются действующие решени...,Средний риск,10000.0,Мухамадиева Динара Фандусовна
2,2,1197746593835,"13 УСТРИЦ, ООО","Торговля оптовая рыбой, ракообразными и моллюс...",NaN,NaN,NaN,Низкий риск,25000.0,Буторина Екатерина Владимировна
3,3,1167847127953,"16-Я РЕСПУБЛИКА, ООО",Торговля оптовая неспециализированная пищевыми...,+7 (495) 0035916\n+7 (800) 1001681,NaN,NaN,Высокий риск,10000.0,Жилина Галина Ивановна
4,4,1121103001018,"21 ВЕК, ООО",Торговля оптовая пивом,+7 (82151) 55207,NaN,NaN,Низкий риск,10000.0,Закирова Наталья Николаевна
...,...,...,...,...,...,...,...,...,...,...
9886,9886,1203600019842,"ЯГОДЫ МИКС, ООО",Торговля оптовая фруктами и овощами,NaN,NaN,NaN,Низкий риск,20000.0,Мильнер Роман Владимирович
9887,9887,1177746445250,"ЯГОДЫ СИБИРИ, ООО",Торговля оптовая фруктами и овощами,+7 (905) 7703286,NaN,NaN,Высокий риск,300000.0,Лебедева Олеся Олеговна
9888,9888,1042127014236,"ЯГУАР, ООО",Торговля оптовая напитками,+7 (8352) 632320\n+7 (8352) 635657\n+7 (8352) ...,NaN,На 19.03.2023 22:05 имеются действующие решени...,Высокий риск,10090000.0,Мухин Дмитрий Алексеевич
9889,9889,1159102132640,"ЯГУАР, ООО",Торговля оптовая фруктами и овощами,+7 (978) 1273228\n+7 (978) 7407340,01.24.29.110 Черешня\n01.25.31.000 Миндаль\n01...,NaN,Низкий риск,10000.0,Буздаков Антон Александрович
9890,9890,1192130009026,"ЯДРИНСКИЙ КООПТОРГ, ООО",Торговля оптовая неспециализированная пищевыми...,+7 (960) 3065036,NaN,NaN,Низкий риск,250000.0,Казамбаева Людмила Виссарионовна

In [61]:
providers.isna().sum().sort_values(ascending=True)

Registration number            0
Регистрационный номер          0
Наименование                   0
Вид деятельности/отрасль       0
Сводный индикатор              0
Уставный капитал, RUB          0
Руководитель - ФИО             0
Телефон                     2193
Предмет поставки            7604
Важная информация           7749
dtype: int64

In [62]:
# providers = providers.drop([
#     'Телефон', 
#          '2022, Среднесписочная численность работников', 
#          'Размер компании', 
#          '2022, Коэффициент текущей ликвидности, %', 
#          '2022, Коэффициент быстрой ликвидности, %', 
#          '2022, Рентабельность капитала (ROE), %', 
#          '2022, Рентабельность активов (ROA), %', 
#          '2022, Коэффициент абсолютной ликвидности, %', 
#          '2022, Себестоимость продаж, RUB', 
#          '2022, Коэффициент оборачиваемости совокупных активов, %', 
#          '2022, Период оборота активов, дни', 
#          '2022, Рентабельность продаж, %', 
#          '2022, Доля себестоимости как процент от выручки, %', 
#          '2022, Запасы, RUB', 
#          '2022, Уставный капитал , RUB', 
#          '2022, Оборачиваемость основных средств, разы', 
#          '2022, Период оборота основных средств, дни', 
#          '2022, Рентабельность активов (п. 1.6 ст.105.8 НК РФ), %', 
#          '2022, Соотношение валовой прибыли к активам компании, %', 
#          '2022, Валовая рентабельность, %', 'Электронный адрес', 
#          'Предмет поставки'], axis=1)

# a = ['Вид деятельности/отрасль', 'Руководитель - ФИО']
# for col in a:
#     providers = providers[providers[col].notna()]

In [63]:
len(providers['Registration number'].tolist())

9891

In [64]:
providers.to_csv('providers.csv')

In [65]:
ratings = pd.read_excel('comments.xlsx').drop(['Comment', 'Grade'], axis=1).reset_index()
ratings.columns = ratings.columns.str.replace('Unnamed: 3', 'rating')
ratings.columns = ratings.columns.str.replace('Name', 'Provider')
ratings.columns = ratings.columns.str.replace('index', 'Registration number')

prov = []*25
for i in range(25):
    random_number = np.random.randint(0, 9891)
    prov.append(random_number)

ratings['Registration number'] = prov
ratings = ratings.reset_index()
ratings.columns = ratings.columns.str.replace('index', 'User_id')

ratings.head()

   User_id  Registration number       Provider  rating
0        0                 8178      Boxes net       1
1        1                 6083  Productov net       1
2        2                 4595        Shop ru       1
3        3                 7603        Bsd sup       1
4        4                 7083    Ok to be ok       3

In [66]:
matrix =[0]*25
for i in range(25):
    for r in ratings[ratings['User_id'] == i]['Registration number'].tolist():
        row = [0]*len(reg_num)
        row[r] = int(ratings['rating'][ratings['User_id'] == i])
    matrix[i] = row
#     print(set(row))
   

ratings = pd.DataFrame(matrix, columns=df.index.tolist()).replace(0, np.nan)
ratings

,0,1,2,3,4,5,6,7,8,9,...,9881,9882,9883,9884,9885,9886,9887,9888,9889,9890
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
ratings.to_csv('ratings0.csv')

In [68]:
ratings = pd.read_csv('ratings0.csv')
ratings.columns = ratings.columns.str.replace('Unnamed: 0', 'User_id')
ratings = pd.melt(ratings, id_vars='User_id', value_vars=ratings.columns[1:]).sort_values(by='User_id').dropna()
ratings

        User_id variable  value
204450        0     8178    1.0
152076        1     6083    1.0
114877        2     4595    1.0
190078        3     7603    1.0
177079        4     7083    3.0
223355        5     8934    3.0
223956        6     8958    3.0
118107        7     4724    4.0
195383        8     7815    5.0
204109        9     8164    5.0
189510       10     7580    5.0
211336       11     8453    5.0
176337       12     7053    5.0
190588       13     7623    5.0
118689       14     4747    5.0
230390       15     9215    5.0
183491       16     7339    5.0
19442        17      777    1.0
137343       18     5493    1.0
54469        19     2178    1.0
37220        20     1488    3.0
243821       21     9752    1.0
205747       22     8229    1.0
106648       23     4265    1.0
84599        24     3383    5.0

In [69]:
ratings = pd.read_csv('ratings.csv')
ratings.columns = ratings.columns.str.replace('Unnamed: 0', 'User_id')

ratings = pd.melt(ratings, id_vars='User_id', value_vars=ratings.columns[1:]).sort_values(by='User_id').dropna()
ratings.columns = ratings.columns.str.replace('value', 'rating')
ratings.columns = ratings.columns.str.replace('variable', 'Registration number')
ratings

ValueError: Per-column arrays must each be 1-dimensional

In [ ]:
ratings.to_csv('ratings.csv')