In [35]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


def item_based_collaborative_filtering(interactions_matrix, top_n=5):
    '''the item-based collaborative filtering approach 
    to generate non-personalized recommendations'''
    
    similarity_matrix = cosine_similarity(interactions_matrix.T)

    num_users, num_items = interactions_matrix.shape
    recommendations = []

    for user_id in range(num_users):
        user_interactions = interactions_matrix[user_id]
        ranked_items = np.argsort(-user_interactions)  # Sort in descending order

        recommended_items = []
        for item_id in ranked_items:
            if len(recommended_items) >= top_n:
                break

            similar_items = similarity_matrix[item_id]
            similar_indices = np.argsort(-similar_items)  # Sort in descending order

            for similar_item_id in similar_indices:
                if similar_item_id != item_id and similar_item_id not in recommended_items:
                    recommended_items.append(similar_item_id)
                    break

        recommendations.append(recommended_items)

    return recommendations

def recommendations(providers, ratings, top_n=5):
    recommend = pd.DataFrame(columns=providers.columns[1:])
    k = 0
    for el in item_based_collaborative_filtering(ratings, top_n)[0]:
        recommend.loc[k] = providers.iloc[el, ]
        k += 1
    return recommend

In [36]:
ratings = pd.read_csv('ratings0.csv').drop(['Unnamed: 0'], axis=1).fillna(0)
ratings.head()

,0,1,2,3,4,5,6,7,8,9,...,9881,9882,9883,9884,9885,9886,9887,9888,9889,9890
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
providers = pd.read_csv('providers.csv').drop(['Unnamed: 0'], axis=1)
providers.head()

,Registration number,Регистрационный номер,Наименование,Вид деятельности/отрасль,Телефон,Предмет поставки,Важная информация,Сводный индикатор,"Уставный капитал, RUB",Руководитель - ФИО
0,0,1142651006398,"1-АЯ ВАТЕР КОМПАНИ, ООО","Торговля оптовая соками, минеральной водой и п...",+7 (879) 3259919,NaN,NaN,Низкий риск,100000.0,Коптиевский Вадим Валерьевич
1,1,1080276000298,"108 ЧК, ООО","Торговля оптовая кофе, чаем, какао и пряностями",+7 (347) 2374074,NaN,На 24.05.2023 22:06 имеются действующие решени...,Средний риск,10000.0,Мухамадиева Динара Фандусовна
2,2,1197746593835,"13 УСТРИЦ, ООО","Торговля оптовая рыбой, ракообразными и моллюс...",NaN,NaN,NaN,Низкий риск,25000.0,Буторина Екатерина Владимировна
3,3,1167847127953,"16-Я РЕСПУБЛИКА, ООО",Торговля оптовая неспециализированная пищевыми...,+7 (495) 0035916\n+7 (800) 1001681,NaN,NaN,Высокий риск,10000.0,Жилина Галина Ивановна
4,4,1121103001018,"21 ВЕК, ООО",Торговля оптовая пивом,+7 (82151) 55207,NaN,NaN,Низкий риск,10000.0,Закирова Наталья Николаевна

In [40]:
# ratings

,0,1,2,3,4,5,6,7,8,9,...,9881,9882,9883,9884,9885,9886,9887,9888,9889,9890
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
recommendations(providers, ratings.to_numpy(), 5)

,Регистрационный номер,Наименование,Вид деятельности/отрасль,Телефон,Предмет поставки,Важная информация,Сводный индикатор,"Уставный капитал, RUB",Руководитель - ФИО
0,1142651006398,"1-АЯ ВАТЕР КОМПАНИ, ООО","Торговля оптовая соками, минеральной водой и п...",+7 (879) 3259919,NaN,NaN,Низкий риск,100000.0,Коптиевский Вадим Валерьевич
1,1054700601097,"РЕСУРС-С, ООО",Торговля оптовая напитками,+7 (81361) 31106,NaN,На 18.02.2022 22:16 имеются действующие решени...,Средний риск,20000.0,Кукин Алексей Михайлович
2,1062303003465,"РЕСУРС-ЮГ, ООО ТК",Торговля оптовая мясом и мясными продуктами,+7 (865) 2364246\n+7 (8652) 748749\n+7 (8652) ...,NaN,NaN,Низкий риск,130000.0,Межгихов Марат Мусалимович
3,1114401003991,"РЕСУРСГРАД, ООО",Торговля оптовая сахаром,+7 (494) 2414742\n+7 (494) 2417051\n+7 (985) 7...,NaN,NaN,Средний риск,10000.0,Ушаков Петр Николаевич
4,1136450015646,"РЕСУРСПРОД ГРУПП, ООО",Торговля оптовая фруктами и овощами,+7 (845) 2726072\n+7 (905) 3207215,NaN,NaN,Низкий риск,10000.0,Шупиков Геннадий Витальевич

In [44]:
# unathorized = recommendations(providers, ratings.to_numpy(), 1000)
# unathorized

,Регистрационный номер,Наименование,Вид деятельности/отрасль,Телефон,Предмет поставки,Важная информация,Сводный индикатор,"Уставный капитал, RUB",Руководитель - ФИО
0,1142651006398,"1-АЯ ВАТЕР КОМПАНИ, ООО","Торговля оптовая соками, минеральной водой и п...",+7 (879) 3259919,NaN,NaN,Низкий риск,100000.0,Коптиевский Вадим Валерьевич
1,1054700601097,"РЕСУРС-С, ООО",Торговля оптовая напитками,+7 (81361) 31106,NaN,На 18.02.2022 22:16 имеются действующие решени...,Средний риск,20000.0,Кукин Алексей Михайлович
2,1062303003465,"РЕСУРС-ЮГ, ООО ТК",Торговля оптовая мясом и мясными продуктами,+7 (865) 2364246\n+7 (8652) 748749\n+7 (8652) ...,NaN,NaN,Низкий риск,130000.0,Межгихов Марат Мусалимович
3,1114401003991,"РЕСУРСГРАД, ООО",Торговля оптовая сахаром,+7 (494) 2414742\n+7 (494) 2417051\n+7 (985) 7...,NaN,NaN,Средний риск,10000.0,Ушаков Петр Николаевич
4,1136450015646,"РЕСУРСПРОД ГРУПП, ООО",Торговля оптовая фруктами и овощами,+7 (845) 2726072\n+7 (905) 3207215,NaN,NaN,Низкий риск,10000.0,Шупиков Геннадий Витальевич
...,...,...,...,...,...,...,...,...,...
995,1142310007333,"САМА ПРИРОДА, ООО","Торговля оптовая кофе, чаем, какао и пряностями",+7 (928) 2476645\n+7 (928) 2413990\n+7 (952) 8...,NaN,NaN,Средний риск,10000.0,Копотилова Алёна Викторовна
996,1172375106144,"САМА ПРИРОДА, ООО","Торговля оптовая кофе, чаем, какао и пряностями",NaN,NaN,На 31.01.2022 16:50 имеются действующие решени...,Средний риск,10000.0,Копотилова Алёна Викторовна
997,1172901013295,"САМАР, ООО",Торговля оптовая фруктами и овощами,+7 (925) 0482082\n+7 (960) 0026858\n+7 (964) 3...,01.25.31.000 Миндаль\n01.13.12.120 Капуста бел...,NaN,Низкий риск,10000.0,Машарипов Аминжон Бахретдинович
998,1196313098816,"САМАРА-МУКА, ООО","Торговля оптовая прочими пищевыми продуктами, ...",NaN,NaN,NaN,Низкий риск,10000.0,Немкин Константин Сергеевич
999,1116318007585,"САМАРА-ХОЛОД, ООО",Торговля оптовая неспециализированная замороже...,+7 (917) 1406587\n+7 (919) 3014987\n+7 (927) 2...,NaN,На 27.12.2022 15:20 имеются действующие решени...,Низкий риск,10000.0,Богатов Дмитрий Николаевич

In [46]:
# unathorized.to_csv('Non_personal recommendations.csv')